from .AutoencoderTask import AutoencoderTask
from .DenoisingTask import DenoisingTask
from .FrameClassificationTask import FrameClassificationTask
from .FrameRegressionTask import FrameRegressionTask
from .NearBondTask import NearBondTask
from .NearestBondTask import NearestBondTask
from .NoisyBondTask import NoisyBondTask
from .PointGroupTask import PointGroupTask
from .ShiftIdentificationTask import ShiftIdentificationTask
